# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-09-05 20:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='objectviewed',
            name='ip_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
