# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-26 16:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartmodel',
            name='subtotal',
            field=models.DecimalField(decimal_places=0, default=0.1, max_digits=10),
        ),
    ]
