# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-29 14:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carts', '0002_cartmodel_subtotal'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=30)),
                ('status', models.CharField(choices=[('created', 'Created'), ('paid', 'Paid'), ('shipped', 'Shipped'), ('Returned', 'Returned')], default='created', max_length=50)),
                ('delivery_total', models.DecimalField(decimal_places=2, default=10.0, max_digits=20)),
                ('total', models.DecimalField(decimal_places=2, default=10.0, max_digits=20)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carts.CartModel')),
            ],
        ),
    ]
