# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-29 14:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='order_id',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
