# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-24 12:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20190824_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='slug',
            field=models.SlugField(blank=True, default='slugname'),
        ),
    ]
