# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-10-26 05:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_productmodel_recommended'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='adinkra',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='couple',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='facial',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='fashion',
            field=models.BooleanField(default=False),
        ),
    ]
